### ISSUE TITLE
sodium-react-native (Bonus)

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1558]
Continuation of [✓ Build sodium-react-native library](https://app.asana.com/0/1189635884316057/1205935083635480/f)

Since the lib is working for our use case all the rest of the tasks can be considered low priority and/or optional.

### Tasks

- [x] add Readme
- [x] write tests
- [ ] fix some types exports
- [x] move repo to either under @synonymdev or sodium-friends organization
- [ ] ask Mathias to free up package name sodium-react-native and republish 
- [ ] move to JSI for better performance leveraging C++ and avoiding bridge de-/serialization.
