### ISSUE TITLE
Native - Import LDK backup to ldk-node

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2040]
## Subtasks
- [x] iOS - LDK state
  - [x] synonymdev/bitkit-ios#3
- [x] #2125
  - [x] synonymdev/bitkit-android/pull/6

**Comment by Jasonvdb** [comment]
LDK state imported successfully on iOS: https://github.com/synonymdev/bitkit-ios/pull/3

**Comment by JeanlChristophe** [comment]
We will probably don't look into Slashtags anytime soon

**Comment by JeanlChristophe** [comment]
Can we close the ticket?
