### ISSUE TITLE
Wallet: Suggestion Cards Findings

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#428]
### Tasks:
- [x] remove "Secure your wallet" card
- [x] add "Buy Bitcoin" card + view
- [x] fix the ordering (see prototype)
- [x] update visual appearance of "Lightning pending" card (after setting up a channel)
- [ ] restore all cards on "Reset Suggestions"

**Comment by limpbrains** [comment]
fixed in #479
Last one has a separate issue
