### ISSUE TITLE
Boost: update UI

### ISSUE THREAD

**Issue by pwltr** [synonymdev/bitkit-react-native#438]
### Tasks:
Prompt:
- [ ] We should propose calculated default fee for the boosting feature (see prototype frame)
- [ ] Tapping the fee could then show this current manual UI (- +) for power users

Activity:
- [ ] A boosted transaction should list boost details in the second line + a boost icon (see prototype frame)
- [x] ~We should remove the boost action button from the list views all (see Slack discussion) and keep it in the transaction details overview.~
